version: "3"

services: 
    # auth:
    #     build:
    #         context: .
    #     ports: 
    #         - "${APP_PORT:-1337}:1337"
    #     volumes: 
    #         - ".:/app"
    mysql:
        image: "mysql:8.0"
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "nodejsMysql2:/var/lib/mysql"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]

volumes:
    nodejsMysql2:
        driver: local